dependencies:
- base >= 4.7 && < 5

executables:
  Deploy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - directory
      - filepath
      - cryptonite
      - bytestring
      - memory
      - digits
      - exact-combinatorics
      - lz4
